import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Typography } from '@mui/material'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Listening Ear safeguarding app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography>Listening Ear Safeguarding app</Typography>
      <Link href="/therapist">Sign in as a therapist</Link> | <Link href="/administrator">Sign in as an administrator</Link>
    </div>
  )
}
