import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, Grid, Typography } from '@mui/material'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Listening Ear safeguarding app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h1" gutterBottom>Listening Ear Safeguarding app</Typography>

      <Grid container justifyContent="center" alignItems="center" spacing={3}>
        <Grid item>
          <Link href="/therapist" passHref>
            <Button variant="contained">Sign in as a therapist</Button>
          </Link>
        </Grid>
        <Grid item>
          <Link href="/administrator" passHref>
            <Button variant="contained">Sign in as an administrator</Button>
          </Link>
        </Grid>
      </Grid>

    </div>
  )
}
